version: "3.7"

services:
    web-page:
        image: davidmoca97/url-shortener
        ports: 
            - 9999:9999
        depends_on:
            - 'db'
        env_file: 
            - .env
        restart: on-failure
    db:
        image: 'mongo:latest'
        container_name: 'mongo'
        ports:
            - '27100:27017'

