version: "3.7"

services:
    web-page:
        build: 
            context: ./
            target: production
        ports: 
            - 9999:9999
        depends_on:
            - 'db'
        env_file: 
            - .env
    db:
        image: 'mongo:latest'
        container_name: 'mongo'
        ports:
            - '27100:27017'

